      *     1       1
      -1 7  6   MW  WW    S -24
      -2 8  -1   MT  WT    S -6
      -3 4  3   MW  WW    S 24
      -4 5  -3   MT  WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      *     2       2
      -1 7  6   MW  WW    S -24
      -2 8  -1   MT  WT    S -6
      -3 4  3   MW  WW    S 24
      -4 5  -3   MT  WT    S 6
      -5 1  -4   MT  WT    T 6
      *     3       3
      -1 7  6   MW  WW    S -24
      -2 8  -1   MT  WT    S -6
      -3 4  3   MW  WW    S 24
      -4 5  -3   MT  WT    S 6
      -5 1  -2   MT  WT    T -6
      *     4       4
      -1 7  6   MW  WW    S -24
      -2 8  -1   MT  WT    S -6
      -3 4  3   MW  WW    S 24
      -4 5  -3   MT  WT    S 6
      -5 -2  -4   ZERO  ZERO    S 22
      *     5       5
      -1 7  6   MW  WW    S -24
      -2 8  -1   MT  WT    S -6
      -3 4  3   MW  WW    S 24
      -4 5  -3   MT  WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      *     6       6
      -1 7  6   MW  WW    S -24
      -2 8  -1   MT  WT    S -6
      -3 4  3   MW  WW    S 24
      -4 5  -3   MT  WT    S 6
      -5 -2  -4   MZ  WZ    S 23
      *
