###########################################################
##                                                       ##
##              ordering width information               ##
##              **************************               ##
##                                                       ##
##      Authors: Pierre Artoisenet (UCL-CP3)             ##
##               Olivier Mattelaer (UCL-CP3)             ##
##                                                       ##
###########################################################
##    file generated automatically                       ##
## JP
###########################################################
## TAG         VALUE
  THIN         
  LARGE        u,d,s,c,g,b
  X            0
